---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "sk-project12-app1"
  labels:
    app: "sk-project12-app1"
spec:
  type: "LoadBalancer"
  selector:
    app: "sk-project12-app1"
  ports:
  - name: "sk-project12-app1-port1"
    protocol: "TCP"
    port: 9093
    targetPort: 9093
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sk-project12-app1"
  namespace: "sk-project12"
  labels:
    app: "sk-project12-app1"
spec:
  selector:
    matchLabels:
      app: "sk-project12-app1"
  replicas: 3
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "sk-project12-app1"
    spec:
      volumes:
      - name: "emptydir"
        emptyDir: {}
      containers:
      - name: "sk-project12-app1-container1"
        image: "cmpharbor.gitcmp.tanzu/mobispoc/ubuntu_16.04_vscode:latest"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: "emptydir"
          mountPath: "/emptydir"
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
